### PR TITLE
handle publication with no return value or that returns empty array

### LINKED ISSUE #28: Exception when publication returns an empty array.
When testing the published data for this collection, `userId = null`, I get `Publish function can only return a Cursor or an array of Cursors`
```js
Meteor.publish('kibanaDashboards', function () {
    //make sure that the user is logged in
    if (this.userId) {
        return KibanaDashboards.find({});
    } else {
        this.stop();
        return [];
    }
});
```
I think the collector should expect empty arrays and `null` values.

### PR DESCRIPTION
**Pull request by ziedmahdi**
This should fix #28

### CODE REVIEW

**Comment by johanbrook** [comment]
Great, thanks!

**Comment by nkahnfr** [comment]
Hi,

**In my case this PR creates a bug rather than fixing one.**

Moving the call to ```this.ready()``` outside the ```if``` block processing the case a publication is returning one or more cursors can break the workflow of publications using low-level interface (added/changed/removed). That kind of publications must call ready once the initial record set is complete and if a call to ready is made before the publication has done its job related test won't pass.

The initial code was a taken directly from the Meteor source code handling publications and I think should remain as it was to be compliant with the behavior described in [Meteor documentation](http://docs.meteor.com/api/pubsub.html#Meteor-publish).

**Please consider rollbacking that PR.** (Personally I had to rollback to v1.0.7 to get my application tests worked again.)
See my comment in #28 for a simple fix.

Thanks.

**Comment by ziedmahdi** [comment]
@nkahnfr where is your comment?

**Comment by nkahnfr** [comment]
@ziedmahdi Just posted.

**Pull request merged**
